config/routes.rb
Probrewtech::Application.routes.draw do
  resources :materials, only: [:index, :show]
  resources :finished_goods, only: :index
  resources :revenues, only: :index
  resources :demands, only: :index

  resources :purchase_orders

  resources :sales_orders

  resources :beers

  resources :recipes

  resources :yeasts

  resources :fermentables

  resources :hops

  resources :positions

  resources :members
  resources :expenses, only: :index

  root to: 'static_pages#home'
  as :user do
      match '/user/confirmation' => 'milia/confirmations#update', via: :put, as: :update_user_confirmation
  end
  
  devise_for :users, :controllers => {
      registrations: 'milia/registrations',
      confirmations: 'milia/confirmations',
      sessions: 'milia/sessions',
      passwords: 'milia/passwords',
  }
  match '/dashboard', as: 'user_root_path', via: 'get', to: 'dashboard#index'
  get "dashboard/index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
.container
  .row
    .col-lg-12
      %h1
        .center
          = @org_name
      .row
        .col-lg-4
          %ul
            = link_to "View Employees", members_path
          %ul
            = link_to "View Positions", positions_path
          %ul
            = link_to "View Hops", hops_path
          %ul
            = link_to "View Fermentables", fermentables_path
          %ul
            = link_to "View Yeasts", yeasts_path
          %ul
            = link_to "View Recipes", recipes_path
          %ul
            = link_to "View Beer", beers_path
          %ul
            = link_to "View Inventory", materials_path
          %ul
            = link_to "View Sales Orders", sales_orders_path
          %ul
            = link_to "View Purchase Orders", purchase_orders_path
          %ul
            = link_to "View Finished Goods", finished_goods_path
        .col-lg-4
          %ul
            = link_to "Estimated Weekly Expenses", expenses_path
          %ul
            = link_to "Weekly Revenues", revenues_path
          %ul
            = link_to "Weekly Demand", demands_path