config/routes.rb
Probrewtech::Application.routes.draw do
  resources :materials, only: [:index, :show]
  resources :finished_goods, only: :index
  resources :revenues, only: :index
  resources :demands, only: :index

  resources :purchase_orders

  resources :sales_orders

  resources :beers

  resources :recipes

  resources :yeasts

  resources :fermentables

  resources :hops

  resources :positions

  resources :members
  resources :expenses, only: :index

  root to: 'static_pages#home'
  as :user do
      match '/user/confirmation' => 'milia/confirmations#update', via: :put, as: :update_user_confirmation
  end
  
  devise_for :users, :controllers => {
      registrations: 'milia/registrations',
      confirmations: 'milia/confirmations',
      sessions: 'milia/sessions',
      passwords: 'milia/passwords',
  }
  match '/dashboard', as: 'user_root_path', via: 'get', to: 'dashboard#index'
  get "dashboard/index"

end

app/models/position.rb
class Position < ActiveRecord::Base
    acts_as_tenant
    has_many :members
    PAY_TYPES = ["Salary", "Hourly"]
    validates :pay_type, presence: true, inclusion: { in: PAY_TYPES }
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render action: 'show', status: :created, location: @position }
      else
        format.html { render action: 'new' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name, :pay_type, :pay_rate, :description)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.haml
= simple_form_for @position do |f|
  - if @position.errors.any?
    #error_explanation
      %h2= "#{pluralize(@position.errors.count, "error")} prohibited this position from being saved:"
      %ul
        - @position.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name, input_html: { class: 'form-control' }
  = f.input :pay_type, input_html: { class: 'form-control' }, collection: Position::PAY_TYPES
  = f.input :pay_rate, input_html: { class: 'form-control' }
  = f.input :description, input_html: { class: 'form-control' }
  .space
  = f.submit 'Save', class: "btn btn-primary btn-block"

app/views/positions/edit.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-3
      .center
        %h1 Editing position

      = render 'form'

      = link_to 'Show', @position
      \|
      = link_to 'Back', positions_path

app/views/positions/index.html.haml
.container
  .row
    .col-lg-12
      - content_for :title, "Employees"
      .center
        %h1 Listing positions
      .col-lg-5
        = link_to 'New Position', new_position_path, class: "btn btn-primary"
        .space
      %table.table.table-hover
        %tr
          %th Name
          %th Pay type
          %th Pay rate
          %th Description
          %th
          %th
          %th

        - @positions.each do |position|
          %tr
            %td= position.name
            %td= position.pay_type
            %td= position.pay_rate
            %td= position.description
            %td= link_to 'Show', position, class: "btn btn-info btn-sm"
            %td= link_to 'Edit', edit_position_path(position), class: "btn btn-default btn-sm"
            %td= link_to 'Destroy', position, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger btn-sm"

app/views/positions/new.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-3
      .center
        %h1 New position

      = render 'form'

      = link_to 'Back', positions_path

app/views/positions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @position.name
%p
  %b Pay type:
  = @position.pay_type
%p
  %b Pay rate:
  = @position.pay_rate
%p
  %b Description:
  = @position.description

= link_to 'Edit', edit_position_path(@position)
\|
= link_to 'Back', positions_path