config/routes.rb
Probrewtech::Application.routes.draw do
  resources :materials, only: [:index, :show]
  resources :finished_goods, only: :index
  resources :revenues, only: :index
  resources :demands, only: :index

  resources :purchase_orders

  resources :sales_orders

  resources :beers

  resources :recipes

  resources :yeasts

  resources :fermentables

  resources :hops

  resources :positions

  resources :members
  resources :expenses, only: :index

  root to: 'static_pages#home'
  as :user do
      match '/user/confirmation' => 'milia/confirmations#update', via: :put, as: :update_user_confirmation
  end
  
  devise_for :users, :controllers => {
      registrations: 'milia/registrations',
      confirmations: 'milia/confirmations',
      sessions: 'milia/sessions',
      passwords: 'milia/passwords',
  }
  match '/dashboard', as: 'user_root_path', via: 'get', to: 'dashboard#index'
  get "dashboard/index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    acts_as_tenant
    SOLID_MEASUREMENTS = ["Pounds", "Kilograms", "Ounces", "Grams"]
    LIQUID_MEASUREMENTS = ["Liters", "Gallons", "Quarts"]
    #fermentables
    has_many :recipe_fermentables, dependent: :destroy
    has_many :fermentables, through: :recipe_fermentables
    accepts_nested_attributes_for :recipe_fermentables
    #hops
    has_many :recipe_hops
    has_many :hops, through: :recipe_hops, dependent: :destroy
    accepts_nested_attributes_for :recipe_hops
    #yeasts has_many :recipe_yeasts
    has_many :recipe_yeasts, dependent: :destroy
    has_many :yeasts, through: :recipe_yeasts
    accepts_nested_attributes_for :recipe_yeasts

    has_many :beers
    has_one :finished_good

    def total_cost
        cost = 0.0
        self.recipe_fermentables.each do |f|
            cost += f.quantity * f.fermentable.price
        end
        self.recipe_yeasts.each do |y|
            cost += y.quantity * y.yeast.price
        end
        self.recipe_hops.each do |h|
            cost += h.quantity * h.hop.price
        end
        cost
    end
    def cost_per_bottle
        total_cost / self.size / 10.666
    end
    def cost_per_keg
        total_cost / self.size * 15.5
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.recipe_fermentables.build
    @recipe.recipe_hops.build
    @recipe.recipe_yeasts.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @finished_good = @recipe.build_finished_good(quantity: 0, measurement: "Gallons")

    respond_to do |format|
      if @recipe.save && @finished_good.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :size, :description, :tenant_id, :fermentation_time, recipe_hops_attributes: [:id, :quantity, :measurement, :hop_id], recipe_fermentables_attributes: [:id, :quantity, :measurement, :fermentable_id], recipe_yeasts_attributes: [:id, :quantity, :measurement, :yeast_id])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.haml
= simple_form_for @recipe do |f|
  - if @recipe.errors.any?
    #error_explanation
      %h2= "#{pluralize(@recipe.errors.count, "error")} prohibited this recipe from being saved:"
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name, input_html: { class: 'form-control' }
  = f.input :size, input_html: { class: 'form-control' }
  = f.input :description, input_html: { class: 'form-control' }
  = f.input :fermentation_time, input_html: { class: 'form-control' }
  .center
    %h3
      Hops
  = f.simple_fields_for :recipe_hops do |rh|
    .col-lg-3
      = rh.input :quantity, input_html: { class: 'form-control' }
    .col-lg-3
      = rh.input :measurement, input_html: { class: 'form-control' }, collection: Recipe::SOLID_MEASUREMENTS
    .col-lg-3
      = rh.association :hop, input_html: { class: 'form-control' }
  .clearfix
  .center
    %h3
      Fermentables
  = f.simple_fields_for :recipe_fermentables do |rf|
    .col-lg-3
      = rf.input :quantity, input_html: { class: 'form-control' }
    .col-lg-3
      = rf.input :measurement, input_html: { class: 'form-control' }, collection: Recipe::SOLID_MEASUREMENTS
    .col-lg-3
      = rf.association :fermentable, input_html: { class: 'form-control' }
  .clearfix
  .center
    %h3
      Yeasts
  = f.simple_fields_for :recipe_yeasts do |ry|
    .col-lg-3
      = ry.input :quantity, input_html: { class: 'form-control' }
    .col-lg-3
      = ry.input :measurement, input_html: { class: 'form-control' }, collection: Recipe::LIQUID_MEASUREMENTS
    .col-lg-3
      = ry.association :yeast, input_html: { class: 'form-control' }
  .clearfix
  .space
  = f.submit 'Save', class: 'btn btn-block btn-primary'

app/views/recipes/edit.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-3
      .center
        %h1 Editing recipe

      = render 'form'

      = link_to 'Show', @recipe
      \|
      = link_to 'Back', recipes_path

app/views/recipes/index.html.haml
.container
  .row
    .col-lg-12
      - content_for :title, "Recipes"
      .center
        %h1 Listing Recipes
      .col-lg-5
        = link_to 'New Recipe', new_recipe_path, class: "btn btn-primary"
        .space
      %table.table.table-hover
        %tr
          %th Name
          %th Size
          %th Description
          %th Fermentation time
          %th Batch Cost
          %th Keg Cost
          %th
          %th
          %th

        - @recipes.each do |recipe|
          %tr
            %td= recipe.name
            %td= recipe.size
            %td= recipe.description
            %td= recipe.fermentation_time
            %td= number_to_currency recipe.total_cost
            %td= number_to_currency recipe.cost_per_keg
            %td= link_to 'Show', recipe, class: 'btn btn-info btn-sm'
            %td= link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-default btn-sm'
            %td= link_to 'Destroy', recipe, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-sm'

app/views/recipes/new.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-3
      .center
        %h1 New recipe

      = render 'form'

      = link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%p#notice= notice

%p
  %b Size:
  = @recipe.size
%p
  %b Description:
  = @recipe.description
%p
  %b Tenant:
  = @recipe.tenant_id
%p
  %b Fermentation time:
  = @recipe.fermentation_time

= link_to 'Edit', edit_recipe_path(@recipe)
\|
= link_to 'Back', recipes_path