config/routes.rb
Probrewtech::Application.routes.draw do
  resources :materials, only: [:index, :show]
  resources :finished_goods, only: :index
  resources :revenues, only: :index
  resources :demands, only: :index

  resources :purchase_orders

  resources :sales_orders

  resources :beers

  resources :recipes

  resources :yeasts

  resources :fermentables

  resources :hops

  resources :positions

  resources :members
  resources :expenses, only: :index

  root to: 'static_pages#home'
  as :user do
      match '/user/confirmation' => 'milia/confirmations#update', via: :put, as: :update_user_confirmation
  end
  
  devise_for :users, :controllers => {
      registrations: 'milia/registrations',
      confirmations: 'milia/confirmations',
      sessions: 'milia/sessions',
      passwords: 'milia/passwords',
  }
  match '/dashboard', as: 'user_root_path', via: 'get', to: 'dashboard#index'
  get "dashboard/index"

end

app/models/yeast.rb
class Yeast < ActiveRecord::Base
    acts_as_tenant
    has_one :material, as: :materiable, dependent: :destroy
    has_many :purchase_line_items, as: :purchasable
end

app/controllers/yeasts_controller.rb
class YeastsController < ApplicationController
  before_action :set_yeast, only: [:show, :edit, :update, :destroy]

  # GET /yeasts
  # GET /yeasts.json
  def index
    @yeasts = Yeast.all
  end

  # GET /yeasts/1
  # GET /yeasts/1.json
  def show
  end

  # GET /yeasts/new
  def new
    @yeast = Yeast.new
  end

  # GET /yeasts/1/edit
  def edit
  end

  # POST /yeasts
  # POST /yeasts.json
  def create
    @yeast = Yeast.new(yeast_params)
    @material = @yeast.build_material(quantity: 0, measurement: 'Gallons')

    respond_to do |format|
      if @yeast.save && @material.save
        format.html { redirect_to @yeast, notice: 'Yeast was successfully created.' }
        format.json { render action: 'show', status: :created, location: @yeast }
      else
        format.html { render action: 'new' }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yeasts/1
  # PATCH/PUT /yeasts/1.json
  def update
    respond_to do |format|
      if @yeast.update(yeast_params)
        format.html { redirect_to @yeast, notice: 'Yeast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yeasts/1
  # DELETE /yeasts/1.json
  def destroy
    @yeast.destroy
    respond_to do |format|
      format.html { redirect_to yeasts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yeast
      @yeast = Yeast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yeast_params
      params.require(:yeast).permit(:name, :product, :laboratory, :form, :attenuation, :type_of, :notes, :price, :tenant_id, :price_per_unit)
    end
end

app/helpers/yeasts_helper.rb
module YeastsHelper
end

app/views/yeasts/_form.html.haml
= simple_form_for @yeast do |f|
  - if @yeast.errors.any?
    #error_explanation
      %h2= "#{pluralize(@yeast.errors.count, "error")} prohibited this yeast from being saved:"
      %ul
        - @yeast.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-lg-12
      = f.input :name, input_html: { class: 'form-control' }
  .row
    .col-lg-12
      = f.input :product, input_html: { class: 'form-control' }
  .row
    .col-lg-12
      = f.input :laboratory, input_html: { class: 'form-control' }
  .row
    .col-lg-12
      = f.input :form, input_html: { class: 'form-control' }
  .row
    .col-lg-12
      = f.input :attenuation, input_html: { class: 'form-control' }
  .row
    .col-lg-12
      = f.input :type_of, input_html: { class: 'form-control' }
  .row
    .col-lg-12
      = f.input :notes, input_html: { class: 'form-control' }
  .row
    .col-lg-6
      = f.input :price, input_html: { class: 'form-control' }
    .col-lg-6
      = f.input :price_per_unit, input_html: { class: 'form-control' }, collection: Recipe::LIQUID_MEASUREMENTS
  .space
  .row
    .col-lg-12
      = f.submit 'Save', class: 'btn btn-primary btn-block'

app/views/yeasts/edit.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-3
      .center
        %h1 Editing yeast

      = render 'form'

      = link_to 'Show', @yeast
      \|
      = link_to 'Back', yeasts_path

app/views/yeasts/index.html.haml
.container
  .row
    .col-lg-12
      - content_for :title, "Yeasts"
      .center
        %h1 Listing Yeasts
      .col-lg-5
        = link_to 'New Yeast', new_yeast_path, class: "btn btn-primary"
        .space
      %table.table.table-hover
        %tr
          %th Name
          %th Product
          %th Laboratory
          %th Form
          %th Attenuation
          %th Type of
          %th Notes
          %th Price
          %th
          %th
          %th

        - @yeasts.each do |yeast|
          %tr
            %td= yeast.name
            %td= yeast.product
            %td= yeast.laboratory
            %td= yeast.form
            %td= yeast.attenuation
            %td= yeast.type_of
            %td= yeast.notes
            %td= yeast.price
            %td= link_to 'Show', yeast, class: 'btn btn-info btn-sm'
            %td= link_to 'Edit', edit_yeast_path(yeast), class: 'btn btn-default btn-sm'
            %td= link_to 'Destroy', yeast, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-sm'

app/views/yeasts/new.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-3
      .center
        %h1 New yeast

      = render 'form'
      = link_to 'Back', yeasts_path

app/views/yeasts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @yeast.name
%p
  %b Product:
  = @yeast.product
%p
  %b Laboratory:
  = @yeast.laboratory
%p
  %b Form:
  = @yeast.form
%p
  %b Attenuation:
  = @yeast.attenuation
%p
  %b Type of:
  = @yeast.type_of
%p
  %b Notes:
  = @yeast.notes
%p
  %b Price:
  = @yeast.price
%p
  %b Tenant:
  = @yeast.tenant_id

= link_to 'Edit', edit_yeast_path(@yeast)
\|
= link_to 'Back', yeasts_path